### ISSUE TITLE
Compatibility issues with node v0.1x

### ISSUE THREAD

**Issue by strarsis** [nrkn/css-select-base-adapter#2]
Object.assign is not natively supported by node v0.1x: 
https://travis-ci.org/svg/svgo/jobs/177451265#L233

Should Object.assign(...) then be implemented differently in this module or by using a polyfill/drop-in 
in the parent module ([svgo](https://github.com/svg/svgo)) instead (this is currently used)?

**Comment by nrkn** [comment]
Please polyfill at your end, supporting  0.1x is too much for me :)

PS svgo is awesome, I use it a lot
