### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by Eli-Black-Work** [nrkn/css-select-base-adapter#3]
Hello,

Would you mind adding a LICENSE file to the project?

**Comment by strarsis** [comment]
@nrkn: Yes, a license file would be nice.

**Comment by Eli-Black-Work** [comment]
Thanks, @nrkn :)

**Comment by opichals** [comment]
@nrkn Could you please do `npm publish` a new patch release (e.g. v0.1.1)?

That would make the https://www.npmjs.com/package/css-select-base-adapter contain the LICENSE file which is required in all distributions for the license to apply.

**Comment by nrkn** [comment]
@opichals - done
